### ISSUE TITLE
Doesn't work with latest minikube 

### ISSUE THREAD

**Issue by benmoss** [kubernetes-sigs/cluster-api-provider-gcp#59]
It looks like minikube v0.30.0 isn't a recent enough version of the k8s API to work with the cluster API libraries being used here. Specifically when following the directions in the README, you'll hit this error when running `clustectl create cluster`:

```
F1128 14:25:40.581898    8057 create_cluster.go:65] unable to update bootstrap cluster endpoint: unable to update cluster endpoint: the server could not find the requested resource (put clusters.cluster.k8s.io test1-b70jo)
```

It looks like the [code here](https://github.com/kubernetes-sigs/cluster-api/blob/5a27d984f9af41aa4f952e7c36a11bfbfb042b83/cmd/clusterctl/clusterdeployer/clusterclient/clusterclient.go#L420) is what fails. The cluster exists, just can't be updated with this API. 

minikube v0.30.0 is running kubernetes v1.10.0. I was able to get past this bug by using https://github.com/kubernetes-sigs/kubeadm-dind-cluster and v1.12 instead.

**Comment by oxddr** [comment]
I had the same problem. AFAIK the root cause it that Kubernetes in versions older than v1.12 doesn't support sub-resources in CRDs, at least not out of the box. 

My workaround was to explicitly state the version of Kubernetes to use by minikube - this can be done by adding a flag to clusterctl invocation `--minikube="kubernetes-version=v1.12.0"`. I'll create a PR to make this explicit.
